apiVersion: v1
kind: PersistentVolume
metadata:
  name: userapi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userapi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
