Vagrant.configure("2") do |config|
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vm.provider :virtualbox do |vb|
        config.vbguest.auto_update = false
      end
    end
  
    config.vm.define "userapi_server" do |server|
      server.vm.box = "ubuntu/focal64"
      config.vm.network "forwarded_port", guest: 80, host: 8080
      config.vm.synced_folder "../userapi", "/home/vagrant/userapi", create: true, type: "rsync",
      rsync__exclude: ["**/__pycache__/", "userapi/data/db.sqlite3", "**/migrations/*",]
      server.vm.provider "virtualbox" do |vb|
        vb.name =  "userapi_server"
        vb.memory = 2048
        vb.cpus = 1
      end
    end

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/run.yml"
      ansible.tags = ["install", "check"]
    end
  
  end
  